"""The one data shape every GPU monitor - simulated or real - produces.

`GPUMetrics` is deliberately shaped like a slightly richer
`UtilizationObservation` (Phase 1): whatever collected it - a
scenario's `UtilizationAction`, `nvidia-smi`, or NVML - reports the
same fields, so nothing downstream (the bridge into `Scheduler`, the
poller, the scheduler itself) needs to know or care where a reading
came from.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional


@dataclass(frozen=True)
class GPUProcessInfo:
    """One process a monitor found using a GPU - purely informational."""

    pid: int
    memory_used_mb: Optional[float] = None
    name: Optional[str] = None


@dataclass(frozen=True)
class GPUMetrics:
    """One GPU's reading at one point in time, from whichever monitor
    produced it.

    ``timestamp`` is the *source's* notion of "now" - a real monitor's
    wall-clock time, or a `Simulator`'s simulated time - never
    generated by the code that consumes this object.
    """

    gpu_id: str
    utilization_percent: float
    memory_used_mb: Optional[float]
    memory_total_mb: Optional[float]
    timestamp: datetime
    processes: List[GPUProcessInfo] = field(default_factory=list)
